---
# tasks file for k3s-role
- name: "** node type"
  debug:
    msg: "k3s_type: {{k3s_type}}"

- include: reset.yml
  when: k3s_reset

- include: pre.yml
- include: download.yml
- include: raspberrypi/main.yml

# only care about the first node(who is generating token)
- include: "master.yml"
  when: master_ip == ansible_host

- include: "{{k3s_type}}.yml"
  when: master_ip != ansible_host


- include: registries.yaml
  when: k3s_registries_enabled