---

- include: "systemd.yml"

- include: "master-token.yml"
  when: master_ip == ansible_host

- name: "** Master ** Create kubectl symlink"
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link

- name: "** Master ** Create crictl symlink"
  file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/crictl
    state: link
