---
- name: "** Reset ** Disable services"
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  failed_when: false
  with_items:
    - k3s

- name: "** Reset ** run kill all script provided by k3s"
  shell:
    cmd: "/usr/local/bin/k3s-killall.sh"
  ignore_errors: true

- name: '** Reset ** pkill -9 -f "k3s/data/[^/]+/bin/containerd-shim-runc"'
  register: pkill_containerd_shim_runc
  command: pkill -9 -f "k3s/data/[^/]+/bin/containerd-shim-runc"
  changed_when: "pkill_containerd_shim_runc.rc == 0"
  failed_when: false

- name: "** Reset ** Umount k3s filesystems"
  include_tasks: umount_with_children.yml
  with_items:
    - /run/k3s
    - /var/lib/kubelet
    - /run/netns
    - /var/lib/rancher/k3s
  loop_control:
    loop_var: mounted_fs

- name: "** Reset ** Remove service files, binaries and data"
  file:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ k3s_systemd_service_file_path }}"
    - "{{ k3s_systemd_environment_file_path }}"
    - /etc/rancher/k3s
    - /var/lib/rancher/k3s
    - /var/lib/kubelet
    - /usr/local/bin/k3s

- name: "** Reset ** daemon_reload"
  systemd:
    daemon_reload: yes
